language: rust
rust: nightly
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8; fi
  - . ./ci/before_install.sh

os:
  - linux
  - osx

script:
  - cargo build --verbose
  - cargo test --verbose

notifications:
  webhooks: http://build.servo.org:54856/travis

